ALTER TABLE planes ALTER COLUMN estado DROP DEFAULT;
ALTER TABLE planes DROP CONSTRAINT IF EXISTS chk_planes_estado;
UPDATE planes SET estado = 'BORRADOR' WHERE estado = 'RESERVADO';
ALTER TABLE planes ADD CONSTRAINT chk_planes_estado
    CHECK (estado IN ('BORRADOR', 'ACTIVO', 'COMPLETADO', 'VENCIDO', 'CANCELADO'));
ALTER TABLE planes ALTER COLUMN estado SET DEFAULT 'BORRADOR';
COMMENT ON COLUMN planes.estado IS
    'Estado contractual: BORRADOR, ACTIVO, COMPLETADO, VENCIDO, CANCELADO.';
