DELETE FROM combo_servicios
WHERE combo_id IN (
    SELECT id
    FROM combos
    WHERE nombre IN (
        'PAQUETE FIT PREMIUM',
        'PAQUETE FIT',
        'QUEMADOR DE GRASA - 1 SESIÓN',
        'QUEMADOR DE GRASA - 3 SESIONES',
        'QUEMADOR DE GRASA - 5 SESIONES',
        'QUEMADOR DE GRASA - 10 SESIONES',
        'MESOTERAPIA DMAE - 1 SESIÓN',
        'MESOTERAPIA DMAE - 3 SESIONES',
        'MESOTERAPIA DMAE - 5 SESIONES',
        'MESOTERAPIA DMAE - 10 SESIONES',
        'E - PULSE BIKE - 1 SESIÓN',
        'E - PULSE BIKE - 5 SESIONES',
        'E - PULSE BIKE - 10 SESIONES',
        'E - PULSE BIKE - 20 SESIONES'
    )
);

DELETE FROM combo_local
WHERE combo_id IN (
    SELECT id
    FROM combos
    WHERE nombre IN (
        'PAQUETE FIT PREMIUM',
        'PAQUETE FIT',
        'QUEMADOR DE GRASA - 1 SESIÓN',
        'QUEMADOR DE GRASA - 3 SESIONES',
        'QUEMADOR DE GRASA - 5 SESIONES',
        'QUEMADOR DE GRASA - 10 SESIONES',
        'MESOTERAPIA DMAE - 1 SESIÓN',
        'MESOTERAPIA DMAE - 3 SESIONES',
        'MESOTERAPIA DMAE - 5 SESIONES',
        'MESOTERAPIA DMAE - 10 SESIONES',
        'E - PULSE BIKE - 1 SESIÓN',
        'E - PULSE BIKE - 5 SESIONES',
        'E - PULSE BIKE - 10 SESIONES',
        'E - PULSE BIKE - 20 SESIONES'
    )
);

DELETE FROM combos
WHERE nombre IN (
    'PAQUETE FIT PREMIUM',
    'PAQUETE FIT',
    'QUEMADOR DE GRASA - 1 SESIÓN',
    'QUEMADOR DE GRASA - 3 SESIONES',
    'QUEMADOR DE GRASA - 5 SESIONES',
    'QUEMADOR DE GRASA - 10 SESIONES',
    'MESOTERAPIA DMAE - 1 SESIÓN',
    'MESOTERAPIA DMAE - 3 SESIONES',
    'MESOTERAPIA DMAE - 5 SESIONES',
    'MESOTERAPIA DMAE - 10 SESIONES',
    'E - PULSE BIKE - 1 SESIÓN',
    'E - PULSE BIKE - 5 SESIONES',
    'E - PULSE BIKE - 10 SESIONES',
    'E - PULSE BIKE - 20 SESIONES'
);
