// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bd/reservas": {
            "post": {
                "description": "Crea una reserva persistida en PostgreSQL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas BD"
                ],
                "summary": "Crear reserva en base de datos",
                "parameters": [
                    {
                        "description": "Datos de la reserva",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.crearReservaPGRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Actualiza una reserva existente en PostgreSQL.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas BD"
                ],
                "summary": "Actualizar reserva en base de datos",
                "parameters": [
                    {
                        "description": "Datos para actualizar la reserva",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.actualizarReservaPGRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/bd/reservas/calendario": {
            "get": {
                "description": "Devuelve reservas agrupadas por local con filtros opcionales.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas BD"
                ],
                "summary": "Listar reservas desde base de datos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nombre del local",
                        "name": "local",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha exacta",
                        "name": "fecha",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha desde",
                        "name": "fecha_desde",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Fecha hasta",
                        "name": "fecha_hasta",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nombre del cliente",
                        "name": "cliente",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "mesa",
                            "bicicleta"
                        ],
                        "type": "string",
                        "description": "Tipo de reserva",
                        "name": "tipo",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar por estado reservado",
                        "name": "reservados",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/bd/reservas/{id}": {
            "get": {
                "description": "Devuelve una reserva de PostgreSQL por su identificador.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas BD"
                ],
                "summary": "Obtener reserva por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la reserva",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/combos": {
            "get": {
                "description": "Devuelve combos filtrados por nombre, categoria, local y sesiones.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogo"
                ],
                "summary": "Listar combos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Busqueda parcial por nombre",
                        "name": "nombre",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Busqueda parcial por categoria",
                        "name": "categoria",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ARANJUEZ",
                            "CENTRO",
                            "SAN MARTIN"
                        ],
                        "type": "string",
                        "description": "Local",
                        "name": "local",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Numero exacto de sesiones",
                        "name": "sesiones",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/reservas": {
            "get": {
                "description": "Devuelve reservas filtradas por local, semana, dia, tipo, cliente y si estan reservadas.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas Sheets"
                ],
                "summary": "Listar reservas desde Google Sheets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nombre del local",
                        "name": "local",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Semana a consultar",
                        "name": "semana",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Dia a consultar",
                        "name": "dia",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "mesa",
                            "bicicleta",
                            "feriado"
                        ],
                        "type": "string",
                        "description": "Tipo de reserva",
                        "name": "tipo",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Nombre del cliente",
                        "name": "cliente",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Filtrar solo reservados",
                        "name": "reservados",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Crea una reserva en uno o varios slots dentro de Google Sheets.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas Sheets"
                ],
                "summary": "Crear reserva en Google Sheets",
                "parameters": [
                    {
                        "description": "Datos de la reserva",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.crearReservaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "207": {
                        "description": "Multi-Status",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Modifica una reserva existente en Google Sheets.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Reservas Sheets"
                ],
                "summary": "Actualizar reserva en Google Sheets",
                "parameters": [
                    {
                        "description": "Datos para actualizar la reserva",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.actualizarReservaRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "207": {
                        "description": "Multi-Status",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        },
        "/servicios": {
            "get": {
                "description": "Devuelve servicios filtrados por nombre, categoria, local y sesiones.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalogo"
                ],
                "summary": "Listar servicios",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Busqueda parcial por nombre",
                        "name": "nombre",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Busqueda parcial por categoria",
                        "name": "categoria",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "ARANJUEZ",
                            "CENTRO",
                            "SAN MARTIN"
                        ],
                        "type": "string",
                        "description": "Local",
                        "name": "local",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Numero exacto de sesiones",
                        "name": "sesiones",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/utils.APIResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.actualizarReservaPGRequest": {
            "type": "object",
            "required": [
                "id",
                "local"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "local": {
                    "type": "string"
                },
                "nueva_fecha": {
                    "type": "string"
                },
                "nueva_hora_desde": {
                    "type": "string"
                },
                "nueva_hora_hasta": {
                    "type": "string"
                },
                "nuevas_notas": {
                    "type": "string"
                },
                "nuevo_precio": {
                    "type": "number"
                },
                "nuevo_servicio": {
                    "type": "string"
                },
                "nuevo_tipo": {
                    "type": "string"
                }
            }
        },
        "handlers.actualizarReservaRequest": {
            "type": "object",
            "required": [
                "cliente",
                "dia",
                "hora",
                "local",
                "semana",
                "tipo"
            ],
            "properties": {
                "cliente": {
                    "type": "string"
                },
                "dia": {
                    "type": "string"
                },
                "hora": {
                    "type": "string"
                },
                "local": {
                    "type": "string"
                },
                "nueva_hora_desde": {
                    "type": "string"
                },
                "nueva_hora_hasta": {
                    "type": "string"
                },
                "nuevo_dia": {
                    "type": "string"
                },
                "nuevo_servicio": {
                    "type": "string"
                },
                "nuevo_tipo": {
                    "type": "string"
                },
                "semana": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                }
            }
        },
        "handlers.crearReservaPGRequest": {
            "type": "object",
            "required": [
                "cliente",
                "fecha",
                "hora_desde",
                "local"
            ],
            "properties": {
                "cliente": {
                    "type": "string"
                },
                "fecha": {
                    "description": "\"2025-04-04\"",
                    "type": "string"
                },
                "hora_desde": {
                    "type": "string"
                },
                "hora_hasta": {
                    "description": "opcional",
                    "type": "string"
                },
                "local": {
                    "type": "string"
                },
                "notas": {
                    "type": "string"
                },
                "plan_id": {
                    "type": "integer"
                },
                "precio": {
                    "type": "number"
                },
                "servicio": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                }
            }
        },
        "handlers.crearReservaRequest": {
            "type": "object",
            "required": [
                "cliente",
                "dia",
                "hora_desde",
                "local",
                "semana",
                "tipo"
            ],
            "properties": {
                "cliente": {
                    "type": "string"
                },
                "dia": {
                    "type": "string"
                },
                "hora_desde": {
                    "type": "string"
                },
                "hora_hasta": {
                    "type": "string"
                },
                "local": {
                    "type": "string"
                },
                "semana": {
                    "type": "string"
                },
                "servicio": {
                    "type": "string"
                },
                "tipo": {
                    "type": "string"
                }
            }
        },
        "utils.APIResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "error": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "v0.1",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Atrevida Fit - Agenda API",
	Description:      "API REST para reservas, servicios, combos y administracion de Atrevida Fit.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
